name: 'Infra Setup'

on:
  workflow_dispatch:

   
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  ARM_CLIENT_CERTIFICATE: ${{ secrets.AZURE_AD_CLIENT_CERTIFICATE }}
  ARM_CLIENT_CERTIFICATE_PASSWORD: ${{ secrets.AZURE_AD_CLIENT_CERTIFICATE_PASSWORD }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
  RG_FOR_TFSTATE: "jjj"
  SA_FOR_TFSTATE: "utfstate"  # Do not change this value
  CONTAINER_FOR_TFSTATE: "terraform" # Do not change this value
  TF_STATE_ACCESSKEY1: ${{ secrets.TF_STATE_ACCESSKEY1 }} 
  
  

jobs:
  terraform:
    name: 'Terraform_Setup'
    runs-on: ubuntu-latest
    environment: DEV
    
    defaults:
      run:
        shell: bash
        working-directory: ./Iac
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: login to az
      run: |
        echo "$ARM_CLIENT_CERTIFICATE" > sfh-ms.pem
        az login --service-principal -u $ARM_CLIENT_ID -p sfh-ms.pem --tenant "$ARM_TENANT_ID"
        az account set --subscription $ARM_SUBSCRIPTION_ID 

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
        terraform_wrapper: false
      
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: |
        terraform init -upgrade -backend-config="access_key=${{ secrets.TF_STATE_ACCESSKEY1 }}" -backend-config="resource_group_name=${{ env.RG_FOR_TFSTATE }}" -backend-config="storage_account_name=${{ env.SA_FOR_TFSTATE }}" -backend-config="container_name=${{ env.CONTAINER_FOR_TFSTATE }}"
      working-directory: ./Iac
      shell: bash

    # Validate the syntax of Terraform working directory
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ./Iac
      shell: bash

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false -no-color -out tf.plan -var-file "terraform.sit.tfvars" -var="spn_client_id=${{ secrets.AZURE_AD_CLIENT_ID }}" -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var="client_certificate_password=${{ secrets.AZURE_AD_CLIENT_CERTIFICATE_PASSWORD }}" -var="tenant_id=${{ secrets.AZURE_AD_TENANT_ID }}"
      working-directory: ./Iac
      shell: bash

  # Apply the generated plan for Terraform
    - name: Terraform Apply
      id: apply
      run: |
        terraform apply -auto-approve tf.plan
      working-directory: ./Iac
      shell: bash
